# Generated by Django 5.2.6 on 2025-11-17 20:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0008_alter_solicitacaocarona_unique_together_and_more'),
        ('pagamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cents', models.PositiveIntegerField()),
                ('abacate_id', models.CharField(blank=True, max_length=128, null=True)),
                ('brCode', models.TextField(blank=True, null=True)),
                ('brCodeBase64', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CREATED', 'Criado'), ('PAID', 'Pago'), ('EXPIRED', 'Expirado'), ('FAILED', 'Falhou')], default='PENDING', max_length=20)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='corrida.corrida')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
