# Generated by Django 5.2.6 on 2025-11-23 01:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0010_corridatemplate_corrida_parent_template'),
        ('pagamentos', '0002_payment_delete_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pagamento', 'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AddField(
            model_name='payment',
            name='billing_url',
            field=models.URLField(blank=True, help_text='URL do checkout (hosted) retornada pela AbacatePay', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='BRL', help_text='Moeda (ISO 4217)', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Quando o QR/charge expira (se disponível)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp em que o pagamento foi confirmado (PAID)', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Ex: PIX, CREDIT_CARD', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='abacate_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['abacate_id'], name='pagamentos__abacate_cc2b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['external_id'], name='pagamentos__externa_7ca236_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='pagamentos__status_44aeb5_idx'),
        ),
    ]
