# Generated by Django 5.2.6 on 2025-11-24 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_alter_payment_options_payment_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEventProcessed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
