# Generated by Django 5.2.6 on 2025-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('solicitacao_recebida', 'Solicitação recebida'), ('solicitacao_respondida', 'Solicitação respondida'), ('inicio_corrida', 'Início de corrida'), ('fim_corrida', 'Fim de corrida'), ('pagamento_confirmado', 'Pagamento confirmado')], max_length=50),
        ),
    ]
