# Generated by Django 5.2.6 on 2025-10-07 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origem', models.CharField(max_length=255)),
                ('destino', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('vagas_disponiveis', models.PositiveIntegerField()),
                ('horario_saida', models.TimeField()),
                ('horario_chegada', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridas_motorista', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
