# Generated by Django 5.2.6 on 2025-10-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0002_alter_corrida_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='bairro_destino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='bairro_origem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='cep_destino',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='cep_origem',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='cidade_destino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='cidade_origem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='estado_destino',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='estado_origem',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='destino',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='origem',
            field=models.CharField(max_length=100),
        ),
    ]
