# Generated by Django 5.2.6 on 2025-10-23 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0003_corrida_bairro_destino_corrida_bairro_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('cancelada', 'Cancelada')], default='ativa', max_length=10),
        ),
    ]
