# Generated by Django 5.2.6 on 2025-11-02 00:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0004_corrida_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corrida',
            name='destino_lat',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='destino_lon',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='distancia_m',
            field=models.FloatField(blank=True, db_index=True, help_text='Distância aproximada da rota em metros', null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='duracao_s',
            field=models.IntegerField(blank=True, help_text='Duração aproximada em segundos', null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='origem_lat',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='origem_lon',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='pontos_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='rota',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='corrida',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
