# Generated by Django 5.2.6 on 2025-11-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0005_corrida_created_at_corrida_destino_lat_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='corrida',
            old_name='updated_at',
            new_name='atualizado_em',
        ),
        migrations.RenameField(
            model_name='corrida',
            old_name='created_at',
            new_name='criado_em',
        ),
        migrations.RemoveField(
            model_name='corrida',
            name='duracao_s',
        ),
        migrations.AddField(
            model_name='corrida',
            name='bbox_max_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='bbox_max_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='bbox_min_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='bbox_min_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='destino_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='destino_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='distancia_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='horario_chegada',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='horario_saida',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='origem_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='origem_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='pontos_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='vagas_disponiveis',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
