# Generated by Django 5.2.6 on 2025-11-07 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0006_rename_updated_at_corrida_atualizado_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCarona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita'), ('RECUSADA', 'Recusada'), ('CANCELADA', 'Cancelada')], default='PENDENTE', max_length=10)),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='corrida.corrida')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
