# Generated by Django 5.2.6 on 2025-11-14 20:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0007_solicitacaocarona'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitacaocarona',
            unique_together={('corrida', 'passageiro')},
        ),
        migrations.AddIndex(
            model_name='solicitacaocarona',
            index=models.Index(fields=['corrida', 'status'], name='corrida_sol_corrida_b7f098_idx'),
        ),
    ]
