# Generated by Django 5.2.6 on 2025-11-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0008_alter_solicitacaocarona_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corrida',
            name='encerrada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corrida',
            name='iniciada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='corrida',
            name='status',
            field=models.CharField(choices=[('ativa', 'Ativa'), ('em_andamento', 'Em andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='ativa', max_length=20),
        ),
    ]
