# Generated by Django 5.2.6 on 2025-11-21 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corrida', '0009_corrida_encerrada_em_corrida_iniciada_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('origem', models.CharField(max_length=100)),
                ('bairro_origem', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade_origem', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_origem', models.CharField(blank=True, max_length=50, null=True)),
                ('cep_origem', models.CharField(blank=True, max_length=10, null=True)),
                ('destino', models.CharField(max_length=100)),
                ('bairro_destino', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade_destino', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_destino', models.CharField(blank=True, max_length=50, null=True)),
                ('cep_destino', models.CharField(blank=True, max_length=10, null=True)),
                ('horario_saida', models.TimeField(blank=True, null=True)),
                ('horario_chegada', models.TimeField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Diariamente'), ('weekly', 'Semanalmente'), ('monthly', 'Mensalmente')], default='weekly', max_length=10)),
                ('days_of_week', models.JSONField(blank=True, default=list)),
                ('max_passengers', models.PositiveIntegerField(default=4)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrida_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Template de Corrida',
                'verbose_name_plural': 'Templates de Corrida',
            },
        ),
        migrations.AddField(
            model_name='corrida',
            name='parent_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='corrida.corridatemplate'),
        ),
    ]
