# Generated by Django 5.2.6 on 2025-09-15 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('Veiculo_id', models.AutoField(primary_key=True, serialize=False)),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('cor', models.CharField(blank=True, max_length=20)),
                ('ano', models.IntegerField()),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='usuarios.usuario')),
            ],
        ),
    ]
