# Generated by Django 5.2.6 on 2025-09-15 03:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=128)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('tipo_usuario', models.CharField(choices=[('MOTORISTA', 'Motorista'), ('PASSAGEIRO', 'Passageiro')], max_length=20)),
                ('data_cadastro', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
