# Generated by Django 5.2.6 on 2025-10-06 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('passageiro', 'Passageiro'), ('motorista', 'Motorista')], default='passageiro', max_length=20, verbose_name='Tipo de Conta'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF')),
                ('placa', models.CharField(blank=True, max_length=8, null=True, verbose_name='Placa do Veículo')),
                ('modelo_veiculo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo do Veículo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_data', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
