# Generated by Django 5.2.6 on 2025-11-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_tipo_usuario_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('passageiro', 'Passageiro'), ('motorista', 'Motorista'), ('admin', 'Administrador')], default='passageiro', max_length=20, verbose_name='Tipo de Conta'),
        ),
    ]
